### ISSUE TITLE
Example dont work on OSX

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-wks-example#1]
It is not possible to run the example on OSX 10.11.

**Comment by prb28** [comment]
I test it on m’y développement machine, and it may have some additional libraries.

Could you please try to run the fsuae binary in a terminal and copy here the result ?

**Comment by Real-MJoe** [comment]
Last login: Sun Nov 25 10:38:21 on ttys000
/Users/joe/Documents/Coding/vscode-amiga-wks-example/bin/osx/fs-uae ; exit;
joe@MBP ~: /Users/joe/Documents/Coding/vscode-amiga-wks-example/bin/osx/fs-uae ; exit;
dyld: Library not loaded: /usr/local/opt/glib/lib/libgthread-2.0.0.dylib
  Referenced from: /Users/joe/Documents/Coding/vscode-amiga-wks-example/bin/osx/fs-uae
  Reason: image not found
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.

**Comment by Real-MJoe** [comment]
now with libgthread-2.0.0.dylib

Last login: Sun Nov 25 10:39:58 on ttys001
joe@MBP ~: /Users/joe/Documents/Coding/vscode-amiga-wks-example/bin/osx/fs-uae ; exit;
dyld: Library not loaded: /usr/local/opt/glib/lib/libgthread-2.0.0.dylib
  Referenced from: /Users/joe/Documents/Coding/vscode-amiga-wks-example/bin/osx/fs-uae
  Reason: no suitable image found.  Did find:
	/usr/local/opt/glib/lib/libgthread-2.0.0.dylib: mach-o, but wrong architecture
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Thx in andvance

**Comment by prb28** [comment]
Could you please try these libs ?
[FS-UAE-osx-libs.zip](https://github.com/prb28/vscode-amiga-wks-example/files/2613330/FS-UAE-osx-libs.zip)

**Comment by Real-MJoe** [comment]
Thanks for the libs. (In your package the libcre.1.dylib was missing.) 
After I created all the directories and copied the dlls to them, the FS-UAE now runs with MS Visual Code! 

Many many thanks for the awesome Addin! I love it, and look forward to the next version.

**Comment by prb28** [comment]
Great!  Thanks! (I will add the libs in the next release).
If you have some feature in mind for the next release feel free to add requests in the github project.

**Comment by prb28** [comment]
I can't find libcre.1.dylib on my mac...
Was it lib**p**cre.1.dylib ?

**Comment by prb28** [comment]
All the libs are added to the release, it seems to work on an "non dev" mac, could you please confirm it's fixed ?

**Comment by Real-MJoe** [comment]
Sorry for the long wait, but the reallife was very presents!
The samples works fine now!

**Comment by prb28** [comment]
Thanks for the feedback ! (I really understand)
