### ISSUE TITLE
sys:gencop: objectnotfound

### ISSUE THREAD

**Issue by StronSon** [prb28/vscode-amiga-wks-example#11]
hello , i am getting this error
![sys_gencop_objectnotfound](https://user-images.githubusercontent.com/88238936/151177928-b977cf81-98a7-4589-b0a6-3219d4236a3d.gif)

**Comment by StronSon** [comment]
could you make a youtube video of the full installation , from installing studio code , installing the plugin , to loading the workspace , to compiling with full instructions as its obvious people are hitting problems as there are no real clear instructions , just a gif and some very vague info on getting it to work , ps on windows 10.

**Comment by StronSon** [comment]
is it out putting as d:\vscode-amiga-wks-example-windows_x64_6\uae\dh0\myprogram , somethings wrong somewhere buddy.

**Comment by StronSon** [comment]
this is all you really need to do , I don't see why you've made it so complicated.

vasmm68k_mot -m68000 -Fhunk -linedebug -o gencop.o gencop.s
vlink -bamigahunk -Bstatic -o compiledfile gencop.o
pause
then copy to dh0: and run 

or not sure if winuae supports direct files but you could winuae.exe compiledfile

anyway good work , but for now il stick to command line and editing in np++ until you fix it all. thank you for trying to make it easier though , all the best.

**Comment by prb28** [comment]
This workspace is intended to be used like this : https://github.com/prb28/vscode-amiga-assembly/wiki/Getting-started#example-workspace
Here is a tutorial : https://www.youtube.com/watch?v=x7OH7HIF5NQ&t=7689s
Be careful to activate the long paths on windows: https://github.com/prb28/vscode-amiga-assembly/wiki/FAQ#the-emulator-starts-but-it-does-not-boot

Maybe I've a complicated mind ;-)
If you are used to do it with a command line, you may not need something more integrated.
