### ISSUE TITLE
Some errors showing on startup under Windows

### ISSUE THREAD

**Issue by Real-MJoe** [prb28/vscode-amiga-wks-example#2]
If i run the FS-UAE from the example i get folllowing errors.  

![image](https://user-images.githubusercontent.com/40276633/55217140-0857e880-51ff-11e9-9486-11c20db4a976.png)

But the emulator runs without problems.

**Comment by prb28** [comment]
On the example workspace there is a minimal set of files. I don't know when these are necessary, I will look further in the code of fs-uae.

**Comment by prb28** [comment]
The launch configuration should set the emulatorWorkingDir in the bin dir:
`            "emulatorWorkingDir": "${workspaceFolder}\\bin\\windows_x64"
`
And the  [bezel dir](https://github.com/prb28/vscode-amiga-wks-example/files/3050507/bezel.zip) should be in *${workspaceFolder}\bin\windows_x64*
You should the file: *${workspaceFolder}\bin\windows_x64\bezel\left-overlay.png* (and 3 other images).
I do not have the audio problem on my win10 config.
