### ISSUE TITLE
created adf can not find hd0:gencop example

### ISSUE THREAD

**Issue by mithrendal** [prb28/vscode-amiga-wks-example#3]
Hi,

Problem: 
when you boot from the created adf, AmigaOS complains that you should insert device hd0

Reason: 
startup-sequence calls hd0:gencop

Solution:
replace hd0: with sys:

(in case you forgot this ancient stuff 😂  sys: is the volume from which it booted. )
With this change it debugs inside from VisualStudio with the integrated fsuae **and** the created adf is also directly executable with any Amiga Emulator.

**Comment by prb28** [comment]
Thanks!
Back in the days I didn’t use to do startup sequences so, I’m a noob in amiga os ;-).
