### ISSUE TITLE
Problem running workspace 'Unexpected return mesage for Program launch command'

### ISSUE THREAD

**Issue by markcox** [prb28/vscode-amiga-wks-example#7]
I get the message 'Unexpected return mesages' when trying to run the workspace. 
Do you know what causes the issue or how to debug the extension to see what commands it is running? 
![image](https://user-images.githubusercontent.com/546040/81498886-d4f4f200-930a-11ea-94c4-184297248101.png)

**Comment by markcox** [comment]
FYI It seems to be working now. 
The problem was this file:
~/Documents/FS-UAE/Configurations/Default.fs-uae
I had to disable options in this file or rename it because the options in that file were being picked up and setting up floppy images.

**Comment by prb28** [comment]
I'm happy you found the solution, I would haven't been my first guess.
