### ISSUE TITLE
Old copperlist pointer not saved to CopperSave on startup.

### ISSUE THREAD

**Issue by tastymushroom** [prb28/vscode-amiga-wks-example#8]
Hi,
First of all fantastic project. Thanks for the effort!

I noticed a small bug in gencop.s
Line 35 you save the old copper pointer to d4, but then you don't store it in CopperSave.
So line 36 should be something like:
              move.l      d4,CopperSave

Then the correct value will be restored at the end.
I did try to push a fix onto a branch but no permissions to do so :-)

Cheers
TastyMushroom

**Comment by prb28** [comment]
Thanks, I'll fix that.

**Comment by tastymushroom** [comment]
Cheers!
I know it’s just a tiny thing, but I thought I’d let you know.

Also would you have any idea why symbols aren’t available during debug if I org my code?
E.g.
If I org my code @ $20000 then breakpoint and type ${CopperSave} then I get an unknown symbol error. If I comment out the ORG $20000 line and try the same thing, I get a good value returned.
Thanks a lot

**Comment by prb28** [comment]
This looks like a bug.

**Comment by prb28** [comment]
Sorry for the delay on this issue. I just forgot it....
I create a new issue on the main project.
