### ISSUE TITLE
Invalid program to debug error

### ISSUE THREAD

**Issue by Bippym** [prb28/vscode-amiga-wks-example#9]
Everything was working fine then suddenly I got the error in the title.i installed the example workspace but error remains. I cannot compile anything. 
![Clipboard Image](https://user-images.githubusercontent.com/21372489/110853321-64f92480-82ab-11eb-8d4e-e723c8adf941.jpg)

**Comment by prb28** [comment]
The build looks failed, does the program file exists ?

**Comment by StronSon** [comment]
i also see the same error if i try to debug , i cant run the compiled c ode either it does not exist or it is not actually being compiled in the dho folder something is wrong but no idea wht, followed all instructions and it just does not work.

**Comment by StronSon** [comment]
could you make a youtube video of the full installation , from installing studio code to loading the workspace , to compiling with full instructions as its obvious people are hitting problems as there are no real clear instructions , just a gif and some vague info.

**Comment by StronSon** [comment]
i also see the same error if i try to debug
